#启动输出信息
banner:
  location: config/banner.txt
  encoding: utf-8

#服务设置
server:
  context-path: /  #应用程序上下文,/ 访问不需写项目名
  session-timeout: 1800
  tomcat:
    max-threads: 1000
    min-spare-threads: 30
  port: 8181
  uri-encoding: utf-8

#配置database
spring:
  #配置开发环境
  profiles:
    active: dev  # 启动时可切换环境java -jar api.jar --spring.profiles.active=dev
  #配置thymeleaf 页面引擎
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    content-type: text/html
    cache: false
    mode: LEGACYHTML5
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  typeAliasesPackage: com.eriz.**.domain
  global-config:
      id-type: 0 #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
      field-strategy: 1
      db-column-underline: false
      capital-mode: false
      sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
      logic-not-delete-value: 0
      logic-delete-value: 1
  configuration:
      map-underscore-to-camel-case: false
      cache-enabled: false